chore(hooks): update pre-commit hook

diff --git a/public/git-hooks/pre-commit b/public/git-hooks/pre-commit
--- a/public/git-hooks/pre-commit
+++ b/public/git-hooks/pre-commit
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
 
+# Сообщение перед ошибкой или другого вывода
+echo "activated hook"
+
+# Проверка линтинга
 cd public || exit 1
-
-echo "Running npm run lint in /public..."
-
 npm run lint
+if [ $? -ne 0 ]; then
+  echo "Linting failed. Please fix the issues before committing."
+  exit 1
+fi
+
+# Если все проверки прошли, коммит продолжается
+exit 0
